export enum LocalEnvPathsEnum {
  APP_ENV = 'APP_ENV',
  APP_NAME = 'APP_NAME',
  APP_PORT = 'APP_PORT',
  DOCKER_SHARED_VOLUME_PATH = 'DOCKER_SHARED_VOLUME_PATH',

  MONGO_SCHEME = 'MONGO_SCHEME',
  MONGO_USERNAME = 'MONGO_USERNAME',
  MONGO_PASSWORD = 'MONGO_PASSWORD',
  MONGO_HOST = 'MONGO_HOST',
  MONGO_PORT = 'MONGO_PORT',
  MONGO_NAME = 'MONGO_NAME',

  JWT_ACCESS_SECRET = 'JWT_ACCESS_SECRET',
  JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET',
  JWT_ACCESS_EXPIRATION = 'JWT_ACCESS_EXPIRATION',
  JWT_REFRESH_EXPIRATION = 'JWT_REFRESH_EXPIRATION',
}
